version: '3.8'

services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        networks:
            - app-network
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes:
            - ./app:/var/www/html
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: ci4
            MYSQL_USER: ci4_user
            MYSQL_PASSWORD: ci4_password
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root_password
        ports:
            - "8080:80"
        networks:
            - app-network
        depends_on:
            - db

volumes:
    mysqldata:

networks:
    app-network:
        driver: bridge